/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Paneles.Clientes;

import Controladores.ctrlClientes;
import Modelos.clsClientes;
import Formatos.formato_Identidad;
import Formatos.formato_Telefono;
import Vistas.Paneles.jpanelClientes;
import java.awt.Frame;

import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author JManu
 */
public class frm_AgregarCliente extends javax.swing.JDialog {

    private static jpanelClientes panelcliente;

    public static void SetPanelagregar(jpanelClientes panel) {
        panelcliente = panel; // Asignar la referencia del panel
    }

    public frm_AgregarCliente(Frame parent) {
        super(parent, "Agregar cliente", true);
        initComponents();
        this.setLocationRelativeTo(parent);

        ((AbstractDocument) txtIdentidad.getDocument()).setDocumentFilter(new formato_Identidad(txtIdentidad));
        ((AbstractDocument) txtTelefono.getDocument()).setDocumentFilter(new formato_Telefono(txtTelefono));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo7 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtIdentidad = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        txtDirec = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        fondo7.setBackground(new java.awt.Color(51, 136, 191));
        fondo7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel50.setText("Agregar Cliente");
        fondo7.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 6, -1, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        fondo7.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 52, 206, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel51.setText("Nombre");
        fondo7.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 54, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel52.setText("Identidad");
        fondo7.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 92, -1, -1));

        txtIdentidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdentidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentidadKeyTyped(evt);
            }
        });
        fondo7.add(txtIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 89, 206, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel53.setText("Telefono");
        fondo7.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 127, -1, -1));

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        fondo7.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 123, 206, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel54.setText("Direccion");
        fondo7.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 164, -1, -1));

        txtDirec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirecKeyTyped(evt);
            }
        });
        fondo7.add(txtDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 162, 206, -1));

        jButton8.setText("Guardar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        fondo7.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        fondo7.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo7, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo7, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (txtNombre.getText().isEmpty() || txtIdentidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos necesarios");
        } else {

            String identidad = txtIdentidad.getText().trim();
            String telefono = txtTelefono.getText().trim();

            if (!validarIdentidad(identidad)) {
                JOptionPane.showMessageDialog(this, "La identidad no es válida.");
                return;
            }

            if (!validarTelefono(telefono)) {
                JOptionPane.showMessageDialog(this, "El número de teléfono no es válido.");
                return;
            }

            ctrlClientes ctrlclient = new ctrlClientes();

            clsClientes client = new clsClientes();
            client.setNombre(txtNombre.getText());
            client.setIdentidad(txtIdentidad.getText());
            client.setTelefono(txtTelefono.getText());
            client.setDireccion(txtDirec.getText());

            if (ctrlclient.guardar()) {
                JOptionPane.showMessageDialog(null, "Se guardo exitosamente");
                panelcliente.cargaTablaCategoria();
            } else {
                JOptionPane.showMessageDialog(null, "Hubo un error al guardar Producto");
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    public boolean validarIdentidad(String identidad) {
        // Validar el formato con guiones
        if (identidad == null || !identidad.matches("\\d{4}-\\d{4}-\\d{5}")) {
            return false;
        }

        // Eliminar guiones para validar que no sea una secuencia repetida
        String limpio = identidad.replaceAll("-", "");
        return !limpio.matches("(\\d)\\1{12}"); // Evita "0000000000000", "1111111111111", etc.
    }

    public boolean validarTelefono(String telefono) {
        if (telefono == null) {
            return false;
        }

        // Verifica el patrón: 8 dígitos en formato XXXX-XXXX
        return telefono.matches("^\\d{4}-\\d{4}$");
    }


    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtIdentidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentidadKeyReleased

    }//GEN-LAST:event_txtIdentidadKeyReleased

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        if (txtNombre.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtIdentidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentidadKeyTyped
        // TODO add your handling code here:
        if (txtIdentidad.getText().length() >= 16) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdentidadKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        if (txtTelefono.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtDirecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirecKeyTyped
        // TODO add your handling code here:
        if (txtDirec.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDirecKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel fondo7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JTextField txtDirec;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
