package Vistas.Paneles;

import Conexion.clsConexion;
import Vistas.Paneles.Clientes.frm_AgregarCliente;
import Vistas.Paneles.Clientes.frm_ModificarCliente;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JManu
 */
public class jpanelClientes extends javax.swing.JPanel {

    private frm_AgregarCliente agreg;
    private frm_ModificarCliente Modf;

    private String nombre, telefono, direccion, estado, identidad;

    public jpanelClientes() {
        initComponents();
      
        frm_AgregarCliente.SetPanelagregar(this);
        frm_ModificarCliente.SetPanelModif(this);
        cargaTablaCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        ScrollProdc = new javax.swing.JScrollPane();
        tablaClient = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarCliente = new javax.swing.JButton();
        cmbFiltro = new javax.swing.JComboBox<>();
        btnModif = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Administrar Clientes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 40, 0, 0);
        add(jLabel1, gridBagConstraints);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activas", "Desactivadas", "Todos" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        add(cmbEstado, gridBagConstraints);

        tablaClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Identidad", "Nombre", "Telefonos", "Direccion", "Estado", "Ultima modificacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClient.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaClientMousePressed(evt);
            }
        });
        ScrollProdc.setViewportView(tablaClient);
        if (tablaClient.getColumnModel().getColumnCount() > 0) {
            tablaClient.getColumnModel().getColumn(0).setResizable(false);
            tablaClient.getColumnModel().getColumn(0).setPreferredWidth(300);
            tablaClient.getColumnModel().getColumn(1).setResizable(false);
            tablaClient.getColumnModel().getColumn(1).setPreferredWidth(300);
            tablaClient.getColumnModel().getColumn(2).setResizable(false);
            tablaClient.getColumnModel().getColumn(2).setPreferredWidth(200);
            tablaClient.getColumnModel().getColumn(3).setResizable(false);
            tablaClient.getColumnModel().getColumn(3).setPreferredWidth(550);
            tablaClient.getColumnModel().getColumn(4).setResizable(false);
            tablaClient.getColumnModel().getColumn(4).setPreferredWidth(110);
            tablaClient.getColumnModel().getColumn(5).setResizable(false);
            tablaClient.getColumnModel().getColumn(5).setPreferredWidth(305);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 750;
        gridBagConstraints.ipady = 455;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 26, 75, 33);
        add(ScrollProdc, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Buscar por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 39, 0, 0);
        add(jLabel2, gridBagConstraints);

        btnAgregarCliente.setBackground(new java.awt.Color(55, 116, 209));
        btnAgregarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCliente.setText("Agregar Cliente");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 26, 0, 0);
        add(btnAgregarCliente, gridBagConstraints);

        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nombre", "Categoria" }));
        cmbFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFiltroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 6, 0, 0);
        add(cmbFiltro, gridBagConstraints);

        btnModif.setBackground(new java.awt.Color(55, 116, 209));
        btnModif.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModif.setForeground(new java.awt.Color(255, 255, 255));
        btnModif.setText("Modificar Cliente");
        btnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 6, 0, 0);
        add(btnModif, gridBagConstraints);

        jLabel3.setText("Mostrar clientes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        add(jLabel3, gridBagConstraints);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 71;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 6, 0, 0);
        add(txtBuscar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        Connection cn = clsConexion.conectar();
        String SQL;
        if ("ID".equals(cmbFiltro.getSelectedItem().toString())) {

            switch (cmbEstado.getSelectedIndex()) {
                case 0:
                    SQL = "select * from tb_cliente where identidad = ? and estado='Activo'";
                    break;
                case 1:
                    SQL = "select * from tb_cliente where identidad = ? and estado='Desactivado'";
                    break;
                default:
                    SQL = "select * from tb_cliente where identidad = ?";
            }

        } else {

            switch (cmbEstado.getSelectedIndex()) {
                case 0:
                    SQL = "select * from tb_cliente where nombre like ? and estado='Activo'";
                    break;
                case 1:
                    SQL = "select * from tb_cliente where nombre like ? and estado='Desactivado'";
                    break;
                default:
                    SQL = "select * from tb_cliente where nombre like ?";
            }
        }

        try {
            if (txtBuscar.getText().isEmpty()) {
                this.cargaTablaCategoria();
            } else {
                PreparedStatement consulta = cn.prepareStatement(SQL);

                if ("ID".equals(cmbFiltro.getSelectedItem().toString())) {
                    String texto = txtBuscar.getText();
                    boolean esNumero = true;

                    // Verificar si el texto contiene solo dígitos
                    for (int i = 0; i < texto.length(); i++) {
                        if (!Character.isDigit(texto.charAt(i))) {
                            esNumero = false;
                            break;
                        }
                    }
                    if (!esNumero) {
                        // Si no es un número, mostrar mensaje de error
                        System.out.println("ERROR dato no valido para ID");
                        txtBuscar.setText("");
                        return;  // Detener la ejecución del código aquí
                    }
                    consulta.setInt(1, Integer.parseInt(txtBuscar.getText()));
                } else {
                    consulta.setString(1, "%" + txtBuscar.getText() + "%");
                }

                ResultSet rs = consulta.executeQuery();
                rellenarTabla(rs);
            }

        } catch (SQLException ex) {
            System.out.println("Error al buscar" + ex);
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed

        if (agreg == null || !agreg.isVisible()) {
            agreg = new frm_AgregarCliente();
            agreg.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "La ventana ya está abierta, ciérrela antes de abrirla nuevamente.");
        }

    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void tablaClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientMousePressed
        int seleccion = tablaClient.rowAtPoint(evt.getPoint());
       
        nombre = String.valueOf(tablaClient.getValueAt(seleccion, 1));
        identidad = String.valueOf(tablaClient.getValueAt(seleccion, 0));
       telefono = String.valueOf(tablaClient.getValueAt(seleccion, 2));
        direccion = String.valueOf(tablaClient.getValueAt(seleccion, 3));
        estado = String.valueOf(tablaClient.getValueAt(seleccion, 4));
    }//GEN-LAST:event_tablaClientMousePressed

    private void cmbFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltroActionPerformed
        txtBuscar.setText("");
        this.cargaTablaCategoria();
    }//GEN-LAST:event_cmbFiltroActionPerformed

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifActionPerformed
        if (identidad == "") {
            JOptionPane.showMessageDialog(null, "Seleccione la categoria");
        } else if (Modf == null || !Modf.isVisible()) {
            Modf = new frm_ModificarCliente();
            Modf.RecibirDatos(nombre, telefono, direccion, estado, identidad);
            Modf.setVisible(true);
            //Le quitamos la asignacion de valor a las variables seleccionada por cursorr

            identidad = "";
        } else {
            JOptionPane.showMessageDialog(null, "La ventana ya está abierta, ciérrela antes de abrirla nuevamente.");
        }
    }//GEN-LAST:event_btnModifActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        cargaTablaCategoria();
    }//GEN-LAST:event_cmbEstadoActionPerformed

//Metodo para mostarar todas las categorias registradas
    public void cargaTablaCategoria() {
        Connection cn = clsConexion.conectar();
        String sql;

        if (cmbEstado.getSelectedIndex() == 0) {
            sql = "select * from tb_cliente where estado='Activo'";
        } else if (cmbEstado.getSelectedIndex() == 1) {
            sql = "select * from tb_cliente where estado='Desactivado'";
        } else {
            sql = "select * from tb_cliente";
        }

        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            rellenarTabla(rs);
            cn.close();
        } catch (SQLException ex) {
            System.out.println("Error en actualizar tabla categoria" + ex);
        }

    }

    private void rellenarTabla(ResultSet rs) throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tablaClient.getModel();  // Obtenemos el modelo de la tabla para manipular los datos
        model.setRowCount(0); // Limpia la tabla antes de actualizar
        while (rs.next()) {
            Object fila[] = new Object[6];
            for (int i = 0; i < 6; i++) {
                fila[i] = rs.getObject(i + 1);
            }
            model.addRow(fila);
        }

       

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollProdc;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnModif;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTable tablaClient;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
