/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Paneles.Producto;

import Conexion.clsConexion;
import Controladores.ctrlProducto;
import Formatos.formato_Precio;
import Modelos.clsProducto;
import Vistas.Paneles.jpanelProductos;
import Formatos.formato_NumerosNaturales;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author JManu
 */
public class frm_ModificarProducto extends javax.swing.JFrame {

    /**
     * Creates new form frm_ModificarProducto
     */
    private static jpanelProductos panelprodc;
    private String NombreInicial;

    public frm_ModificarProducto() {
        initComponents();
        CargarCMB();
        this.setLocationRelativeTo(null);
        this.setTitle("Modificar Producto");
         ((AbstractDocument) txtCant.getDocument()).setDocumentFilter(new formato_NumerosNaturales());
          ((AbstractDocument) txtPrec.getDocument()).setDocumentFilter(new formato_Precio());
    }

    public static void SetPanelmodf(jpanelProductos panel) {
        panelprodc = panel; // Asignar la referencia del panel
    }

    public void RecibirDatos(String Id, String nom, String desc, double prec, int cant, String cate, String est) {
        txtCod.setText(Id);
        txtNom.setText(nom);
        txtDesc.setText(desc);
        txtPrec.setText(prec + "");
        txtCant.setText(cant + "");
        cmbCategoria.setSelectedItem(cate);
        NombreInicial = nom;
        if (est.equals("Activo")) {
            cmbEstado.setSelectedIndex(0);
        } else {
            cmbEstado.setSelectedIndex(1);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrec = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(51, 136, 191));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Modificar Producto");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        txtCod.setEditable(false);
        txtCod.setEnabled(false);
        fondo.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 52, 206, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Codigo Producto");
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 54, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 92, -1, -1));
        fondo.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 89, 206, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 127, -1, -1));

        txtCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantKeyReleased(evt);
            }
        });
        fondo.add(txtCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 123, 206, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Precio de venta");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 164, -1, -1));

        txtPrec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecKeyReleased(evt);
            }
        });
        fondo.add(txtPrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 162, 206, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Descripcion");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 207, -1, -1));
        fondo.add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 202, 206, -1));

        cmbCategoria.setEditable(true);
        fondo.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 244, 206, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nombre de Categoria");
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 246, -1, -1));

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        jLabel8.setText("Estado");
        fondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Desactivado" }));
        fondo.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        fondo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtCant.getText().isEmpty() || txtPrec.getText().isEmpty() || cmbCategoria.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Rellene todos los campos");
        } else {

            ctrlProducto ctrlprod = new ctrlProducto();

            if (!ctrlprod.existeProducto(txtCod.getText(), txtNom.getText(), "Modificar") || txtNom.getText().equals(NombreInicial)) {
                clsProducto prodc = new clsProducto();
                prodc.setCantidad(Integer.parseInt(txtCant.getText()));
                prodc.setDescripcion(txtDesc.getText());
                prodc.setID_Producto(txtCod.getText());
                prodc.setCategoria(cmbCategoria.getSelectedItem().toString());
                prodc.setNombre(txtNom.getText());
                prodc.setPrecio_venta(Double.parseDouble(txtPrec.getText()));
                prodc.setEstado(cmbEstado.getSelectedItem().toString());

                if (ctrlprod.modificar()) {
                    JOptionPane.showMessageDialog(null, "Se Modifico exitosamente");
                    panelprodc.cargaTablaCategoria();
                } else {
                    JOptionPane.showMessageDialog(null, "Hubo un error al modificar Producto");
                }
            } else {
                JOptionPane.showMessageDialog(null, ctrlprod.mens);
            }

        }

        this.dispose();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPrecKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecKeyReleased
  

    }//GEN-LAST:event_txtPrecKeyReleased

    private void txtCantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantKeyReleased
       
    }//GEN-LAST:event_txtCantKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CargarCMB() {
        Connection cn = clsConexion.conectar();
        String sql = "select nombre from tb_categoria where estado='Activo'";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            cmbCategoria.removeAllItems();
            cmbCategoria.addItem("Ingrese la categoria: ");
            while (rs.next()) {
                cmbCategoria.addItem(rs.getString("nombre"));
            }

            cn.close();
        } catch (SQLException ex) {
            System.out.println("Error en actualizar tabla categoria" + ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_ModificarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrec;
    // End of variables declaration//GEN-END:variables
}
